
import { Translations, Language, RegionGroup, GalleryItem } from './types';

export const LOGO_SRC = "./logo.png"; 

// CONFIGURATION FOR MONETIZATION
export const PAYMENT_LINK = "https://www.paypal.com/myaccount/home"; // <--- PUT YOUR STRIPE/PAYPAL LINK HERE
export const VALID_LICENSE_KEY = "GEMINI-PRO"; // <--- THE CODE USERS ENTER TO UNLOCK

export const DEFAULT_STYLES = [
  "Cinematic", "Photorealistic", "Anime", "Cyberpunk", "Steampunk", 
  "Oil Painting", "Watercolor", "3D Render", "Unreal Engine 5", "Octane Render",
  "Studio Ghibli", "Pixel Art", "Vaporwave", "Noir", "Concept Art",
  "Ukiyo-e", "Low Poly", "Isometric", "Line Art", "Pop Art", 
  "Vintage Photography", "Polaroid", "Macro Photography", "Minimalist"
];

export const REGIONS: RegionGroup[] = [
  { 
    region: 'Global / Common', 
    langs: [
      { code: 'en', label: 'English', flag: '🇺🇸' },
    ] 
  },
  { 
    region: 'Europe', 
    langs: [
      { code: 'fr', label: 'Français', flag: '🇫🇷' },
      { code: 'de', label: 'Deutsch', flag: '🇩🇪' },
      { code: 'es', label: 'Español', flag: '🇪🇸' },
      { code: 'it', label: 'Italiano', flag: '🇮🇹' },
      { code: 'pt', label: 'Português', flag: '🇵🇹' },
      { code: 'nl', label: 'Nederlands', flag: '🇳🇱' },
      { code: 'ru', label: 'Русский', flag: '🇷🇺' },
      { code: 'pl', label: 'Polski', flag: '🇵🇱' },
      { code: 'cs', label: 'Čeština', flag: '🇨🇿' },
      { code: 'tr', label: 'Türkçe', flag: '🇹🇷' },
    ] 
  },
  { 
    region: 'Asia & Pacific', 
    langs: [
      { code: 'zh', label: '中文 (Chinese)', flag: '🇨🇳' },
      { code: 'ja', label: '日本語 (Japanese)', flag: '🇯🇵' },
      { code: 'ko', label: '한국어 (Korean)', flag: '🇰🇷' },
      { code: 'hi', label: 'हिन्दी (Hindi)', flag: '🇮🇳' },
      { code: 'th', label: 'ไทย (Thai)', flag: '🇹🇭' },
      { code: 'vi', label: 'Tiếng Việt', flag: '🇻🇳' },
      { code: 'id', label: 'Bahasa Indonesia', flag: '🇮🇩' },
    ] 
  },
  { 
    region: 'Middle East', 
    langs: [
      { code: 'ar', label: 'العربية (Arabic)', flag: '🇸🇦' },
    ] 
  },
];

export const GALLERY_ITEMS: GalleryItem[] = [
  {
    id: 'cyberpunk',
    src: 'https://images.unsplash.com/photo-1605218427306-635ba2439af2?w=800&q=80',
    alt: 'Neon Cityscape',
    style: 'Cyberpunk',
    promptResponse: {
      english: "A futuristic cyberpunk city street at night, drenched in rain and illuminated by vibrant neon signs in pink and cyan. High-tech skyscrapers tower in the background with holographic advertisements. The street is reflective, capturing the neon lights. Cinematic lighting, highly detailed, photorealistic 8k render, Unreal Engine 5 style.",
      translated: null,
      variations: []
    }
  },
  {
    id: 'oil-painting',
    src: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=800&q=80',
    alt: 'Abstract Art',
    style: 'Oil Painting',
    promptResponse: {
      english: "An expressive oil painting utilizing thick impasto brushstrokes. A blend of vibrant orange, teal, and gold colors swirling together in an abstract composition. Textured surface, visible canvas grain, classical technique mixed with modern abstraction. Emotional and dynamic lighting.",
      translated: null,
      variations: []
    }
  },
  {
    id: 'fantasy',
    src: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&q=80',
    alt: 'Mystic Forest',
    style: 'Fantasy Landscape',
    promptResponse: {
      english: "A mystical forest landscape with ancient, towering trees and glowing ethereal lights floating in the air. Foggy atmosphere with soft sunlight filtering through the canopy (god rays). Enchanted mood, digital art style, fantasy concept art, highly detailed vegetation.",
      translated: null,
      variations: []
    }
  },
  {
    id: '3d-character',
    src: 'https://images.unsplash.com/photo-1618331835717-801e976710b2?w=800&q=80',
    alt: 'Cute Robot',
    style: '3D Render',
    promptResponse: {
      english: "A cute, stylized 3D render of a small friendly robot with glowing blue eyes and a sleek white finish. Soft studio lighting, bokeh background, octane render style, high fidelity materials, plastic and metal textures, Pixar-style character design.",
      translated: null,
      variations: []
    }
  },
  {
    id: 'watercolor',
    src: 'https://images.unsplash.com/photo-1541963463532-d68292c34b19?w=800&q=80',
    alt: 'Mountain Landscape',
    style: 'Watercolor',
    promptResponse: {
      english: "A delicate watercolor painting of a serene mountain landscape. Soft washes of blue and grey for the misty mountains, fading into white paper. Loose, expressive brushwork, ink outlines defining the trees in the foreground. Minimalist, calming atmosphere, traditional art style.",
      translated: null,
      variations: []
    }
  },
  {
    id: 'macro',
    src: 'https://images.unsplash.com/photo-1485178575877-1a13bf489dfe?w=800&q=80',
    alt: 'Water Drop',
    style: 'Macro Photography',
    promptResponse: {
      english: "Extreme close-up macro photography of a water droplet on a green leaf. The droplet acts as a lens, reflecting the background. Razor sharp focus on the droplet, shallow depth of field (bokeh), vibrant green tones, natural lighting, high resolution texture detail.",
      translated: null,
      variations: []
    }
  }
];

const BASE_EN: Translations = {
  title: "VisionCraft AI",
  subtitle: "Unlock the secret prompts behind your pixels. Get detailed artistic descriptions and style prompts to recreate any image with AI.",
  uploadTitle: "Click to upload an image",
  uploadDesc: "or drag and drop (JPG, PNG, WEBP)",
  analyzeBtn: "Generate Prompt",
  analyzing: "Analyzing Image...",
  resultTitle: "Generated Prompt",
  copyBtn: "Copy",
  copied: "Copied!",
  footerText: "Developed by",
  footerLinkText: "zaki iyed",
  errorGeneric: "Something went wrong. Please try again.",
  errorQuota: "API quota exceeded. Please try again later.",
  errorRateLimit: "Server is busy. Please wait a moment.",
  resetBtn: "Upload New Image",
  saveImageBtn: "Save Image",
  tabEnglish: "English Prompt",
  tabTranslated: "Translation",
  tabCustom: "Custom Style",
  complexityLabel: "Prompt Detail Level",
  complexShort: "Concise",
  complexNormal: "Standard",
  complexLong: "Deep Analysis",
  customStyleLabel: "Target Style (Optional)",
  customStylePlaceholder: "e.g., Cyberpunk, Van Gogh...",
  presetsLabel: "Presets",
  savePresetPlaceholder: "Preset name...",
  saveBtn: "Save",
  noPresets: "No saved presets",
  editPreset: "Edit Preset",
  updateBtn: "Update",
  cancelBtn: "Cancel",
  goPremium: "Go Premium",
  premiumActive: "PRO Active",
  premiumModalTitle: "Unlock Professional Features",
  premiumBenefit1: "Powered by Gemini 1.5 Pro (Smarter Model)",
  premiumBenefit2: "Generate 3 Extra Style Variations (Anime, Cinematic, Art)",
  premiumBenefit3: "Detailed Technical Analysis",
  upgradeBtn: "Buy Premium Access ($4.99)",
  securePayment: "Secure payment via PayPal",
  variationsTitle: "Style Variations (PRO)",
  haveCode: "Already purchased? Enter code:",
  enterCode: "License Key (e.g. GEMINI-PRO)",
  unlockBtn: "Activate",
  invalidCode: "Invalid License Key",
  shareTwitter: "Post on X",
  shareInstagram: "Post on Instagram",
  sharePinterest: "Pin on Pinterest",
  shareReddit: "Share on Reddit",
  shareSystem: "Share (Image + Text)",
  themeLight: "Switch to Light Mode",
  themeDark: "Switch to Dark Mode",
  galleryTitle: "Try these examples",
  generateVideoBtn: "Generate Video Preview",
  generatingVideo: "Generating Video (this takes ~1-2 mins)...",
  videoTitle: "AI Video (Veo)",
  videoError: "Failed to generate video. Please try again."
};

export const TEXTS: Record<Language, Translations> = {
  en: BASE_EN,
  ar: {
    title: "VisionCraft AI",
    subtitle: "اكتشف الأسرار الفنية خلف صورك. احصل على وصف دقيق ومحترف لإعادة ابتكار أي صورة باستخدام الذكاء الاصطناعي.",
    uploadTitle: "اضغط لرفع صورة",
    uploadDesc: "أو قم بسحب وإفلات الملف (JPG, PNG, WEBP)",
    analyzeBtn: "توليد الوصف",
    analyzing: "جاري تحليل الصورة...",
    resultTitle: "الوصف المستخرج",
    copyBtn: "نسخ",
    copied: "تم النسخ!",
    footerText: "تم التطوير من طرف",
    footerLinkText: "zaki iyed",
    errorGeneric: "حدث خطأ ما. يرجى المحاولة مرة أخرى.",
    errorQuota: "تم تجاوز حصة API. يرجى المحاولة لاحقاً.",
    errorRateLimit: "الخادم مشغول حالياً. يرجى الانتظار.",
    resetBtn: "رفع صورة جديدة",
    saveImageBtn: "حفظ الصورة",
    tabEnglish: "الوصف بالإنجليزي",
    tabTranslated: "الترجمة العربية",
    tabCustom: "أسلوب مخصص",
    complexityLabel: "مستوى التفاصيل",
    complexShort: "موجز",
    complexNormal: "قياسي",
    complexLong: "تحليل عميق",
    customStyleLabel: "نمط فني (اختياري)",
    customStylePlaceholder: "مثلاً: سايبربانك، فان جوخ...",
    presetsLabel: "الإعدادات المحفوظة",
    savePresetPlaceholder: "اسم الإعداد...",
    saveBtn: "حفظ",
    noPresets: "لا توجد إعدادات محفوظة",
    editPreset: "تعديل الإعداد",
    updateBtn: "تحديث",
    cancelBtn: "إلغاء",
    goPremium: "ترقية للحساب المميز",
    premiumActive: "عضوية مميزة",
    premiumModalTitle: "احصل على مميزات احترافية",
    premiumBenefit1: "مدعوم بنموذج Gemini 1.5 Pro الأذكى",
    premiumBenefit2: "توليد 3 أنماط إضافية (أنمي، سينمائي، فني)",
    premiumBenefit3: "تحليل تقني دقيق ومفصل",
    upgradeBtn: "شراء النسخة الكاملة ($4.99)",
    securePayment: "دفع آمن عبر PayPal",
    variationsTitle: "تنويعات فنية (بريميوم)",
    haveCode: "اشتريت بالفعل؟ أدخل الرمز:",
    enterCode: "مفتاح الترخيص",
    unlockBtn: "تفعيل",
    invalidCode: "مفتاح غير صحيح",
    shareTwitter: "نشر على X",
    shareInstagram: "نشر على Instagram",
    sharePinterest: "حفظ في Pinterest",
    shareReddit: "نشر في Reddit",
    shareSystem: "مشاركة (صورة + نص)",
    themeLight: "تفعيل الوضع النهاري",
    themeDark: "تفعيل الوضع الليلي",
    galleryTitle: "جرب هذه الأمثلة",
    generateVideoBtn: "توليد فيديو معاينة",
    generatingVideo: "جاري توليد الفيديو (يستغرق 1-2 دقيقة)...",
    videoTitle: "فيديو بالذكاء الاصطناعي (Veo)",
    videoError: "فشل توليد الفيديو. حاول مرة أخرى."
  },
  fr: {
    title: "VisionCraft AI",
    subtitle: "Révélez les prompts cachés derrière vos pixels. Obtenez une description artistique détaillée pour recréer n'importe quelle image avec l'IA.",
    uploadTitle: "Cliquez pour télécharger",
    uploadDesc: "ou glissez-déposez (JPG, PNG, WEBP)",
    analyzeBtn: "Générer le Prompt",
    analyzing: "Analyse en cours...",
    resultTitle: "Prompt Généré",
    copyBtn: "Copier",
    copied: "Copié !",
    footerText: "Développé par",
    footerLinkText: "zaki iyed",
    errorGeneric: "Une erreur s'est produite. Veuillez réessayer.",
    errorQuota: "Quota API dépassé. Veuillez réessayer plus tard.",
    errorRateLimit: "Serveur surchargé. Veuillez patienter.",
    resetBtn: "Nouvelle image",
    saveImageBtn: "Enregistrer l'image",
    tabEnglish: "Prompt Anglais",
    tabTranslated: "Traduction",
    tabCustom: "Style Personnalisé",
    complexityLabel: "Niveau de Détail",
    complexShort: "Concis",
    complexNormal: "Standard",
    complexLong: "Analyse Approfondie",
    customStyleLabel: "Style Cible (Optionnel)",
    customStylePlaceholder: "ex: Cyberpunk, Van Gogh...",
    presetsLabel: "Préréglages",
    savePresetPlaceholder: "Nom du réglage...",
    saveBtn: "Enregistrer",
    noPresets: "Aucun préréglage",
    editPreset: "Modifier",
    updateBtn: "Mettre à jour",
    cancelBtn: "Annuler",
    goPremium: "Passer Premium",
    premiumActive: "Mode PRO",
    premiumModalTitle: "Débloquez les fonctionnalités Pro",
    premiumBenefit1: "Propulsé par Gemini 1.5 Pro (Modèle supérieur)",
    premiumBenefit2: "3 Variations de style (Anime, Cinématique, Art)",
    premiumBenefit3: "Analyse technique détaillée",
    upgradeBtn: "Acheter l'accès Premium ($4.99)",
    securePayment: "Paiement sécurisé via PayPal",
    variationsTitle: "Variations de Style (PRO)",
    haveCode: "Déjà acheté ? Entrez le code :",
    enterCode: "Clé de licence",
    unlockBtn: "Activer",
    invalidCode: "Clé invalide",
    shareTwitter: "Partager sur X",
    shareInstagram: "Partager sur Instagram",
    sharePinterest: "Épingler sur Pinterest",
    shareReddit: "Partager sur Reddit",
    shareSystem: "Partager (Image + Texte)",
    themeLight: "Mode clair",
    themeDark: "Mode sombre",
    galleryTitle: "Essayez ces exemples",
    generateVideoBtn: "Générer Vidéo (Aperçu)",
    generatingVideo: "Génération vidéo en cours (~1-2 min)...",
    videoTitle: "Vidéo IA (Veo)",
    videoError: "Échec de la génération vidéo."
  },
  ru: {
    title: "VisionCraft AI",
    subtitle: "Раскройте секретные промпты ваших изображений. Получите детальное описание и стиль для воссоздания любой картинки с помощью ИИ.",
    uploadTitle: "Нажмите для загрузки",
    uploadDesc: "или перетащите сюда (JPG, PNG, WEBP)",
    analyzeBtn: "Сгенерировать промпт",
    analyzing: "Анализ изображения...",
    resultTitle: "Сгенерированный промпт",
    copyBtn: "Копировать",
    copied: "Скопировано!",
    footerText: "Разработано",
    footerLinkText: "zaki iyed",
    errorGeneric: "Что-то пошло не так. Пожалуйста, попробуйте снова.",
    errorQuota: "Квота API исчерпана. Попробуйте позже.",
    errorRateLimit: "Сервер перегружен. Подождите.",
    resetBtn: "Загрузить новое",
    saveImageBtn: "Сохранить изображение",
    tabEnglish: "English Prompt",
    tabTranslated: "Перевод",
    tabCustom: "Свой стиль",
    complexityLabel: "Уровень детализации",
    complexShort: "Кратко",
    complexNormal: "Стандарт",
    complexLong: "Глубокий анализ",
    customStyleLabel: "Целевой стиль (Опционально)",
    customStylePlaceholder: "напр. Киберпанк, Ван Гог...",
    presetsLabel: "Пресеты",
    savePresetPlaceholder: "Имя пресета...",
    saveBtn: "Сохранить",
    noPresets: "Нет пресетов",
    editPreset: "Редактировать",
    updateBtn: "Обновить",
    cancelBtn: "Отмена",
    goPremium: "Премиум",
    premiumActive: "PRO Активен",
    premiumModalTitle: "Получите профессиональные функции",
    premiumBenefit1: "На базе Gemini 1.5 Pro (Умная модель)",
    premiumBenefit2: "3 варианта стиля (Аниме, Кино, Арт)",
    premiumBenefit3: "Детальный технический анализ",
    upgradeBtn: "Купить Premium ($4.99)",
    securePayment: "Безопасная оплата через PayPal",
    variationsTitle: "Варианты стилей (PRO)",
    haveCode: "Уже купили? Введите код:",
    enterCode: "Лицензионный ключ",
    unlockBtn: "Активировать",
    invalidCode: "Неверный ключ",
    shareTwitter: "Опубликовать в X",
    shareInstagram: "Опубликовать в Instagram",
    sharePinterest: "Запинить в Pinterest",
    shareReddit: "Поделиться на Reddit",
    shareSystem: "Поделиться",
    themeLight: "Светлая тема",
    themeDark: "Темная тема",
    galleryTitle: "Попробуйте эти примеры",
    generateVideoBtn: "Создать видео-превью",
    generatingVideo: "Генерация видео (~1-2 мин)...",
    videoTitle: "AI Видео (Veo)",
    videoError: "Ошибка генерации видео."
  },
  cs: {
    title: "VisionCraft AI",
    subtitle: "Odhalte tajemné prompty za pixely. Získejte detailní umělecký popis pro znovuvytvoření jakéhokoli obrázku pomocí AI.",
    uploadTitle: "Klikněte pro nahrání",
    uploadDesc: "nebo přetáhněte (JPG, PNG, WEBP)",
    analyzeBtn: "Generovat prompt",
    analyzing: "Analyzuji obrázek...",
    resultTitle: "Vygenerovaný prompt",
    copyBtn: "Kopírovat",
    copied: "Zkopírováno!",
    footerText: "Vývojář",
    footerLinkText: "zaki iyed",
    errorGeneric: "Něco se pokazilo. Zkuste to prosím znovu.",
    errorQuota: "Vyčerpána kvóta API. Zkuste to později.",
    errorRateLimit: "Server je přetížen. Čekejte prosím.",
    resetBtn: "Nahrát nový obrázek",
    saveImageBtn: "Uložit obrázek",
    tabEnglish: "Anglický prompt",
    tabTranslated: "Překlad",
    tabCustom: "Vlastní styl",
    complexityLabel: "Úroveň detailů",
    complexShort: "Stručné",
    complexNormal: "Standardní",
    complexLong: "Hloubková analýza",
    customStyleLabel: "Cílový styl (Volitelné)",
    customStylePlaceholder: "např. Cyberpunk, Van Gogh...",
    presetsLabel: "Předvolby",
    savePresetPlaceholder: "Název předvolby...",
    saveBtn: "Uložit",
    noPresets: "Žádné předvolby",
    editPreset: "Upravit",
    updateBtn: "Aktualizovat",
    cancelBtn: "Zrušit",
    goPremium: "Přejít na Premium",
    premiumActive: "PRO Aktivní",
    premiumModalTitle: "Odemkněte profesionální funkce",
    premiumBenefit1: "Poháněno Gemini 1.5 Pro (Chytřejší model)",
    premiumBenefit2: "3 stylové variace (Anime, Cinematic, Art)",
    premiumBenefit3: "Detailní technická analýza",
    upgradeBtn: "Koupit Premium přístup ($4.99)",
    securePayment: "Bezpečná platba přes PayPal",
    variationsTitle: "Stylové variace (PRO)",
    haveCode: "Již zakoupeno? Zadejte kód:",
    enterCode: "Licenční klíč",
    unlockBtn: "Aktivovat",
    invalidCode: "Neplatný klíč",
    shareTwitter: "Sdílet na X",
    shareInstagram: "Sdílet na Instagram",
    sharePinterest: "Uložit na Pinterest",
    shareReddit: "Sdílet na Reddit",
    shareSystem: "Sdílet",
    themeLight: "Světlý režim",
    themeDark: "Tmavý režim",
    galleryTitle: "Zkuste tyto příklady",
    generateVideoBtn: "Generovat video ukázku",
    generatingVideo: "Generování videa (~1-2 min)...",
    videoTitle: "AI Video (Veo)",
    videoError: "Generování videa selhalo."
  },
  es: {
    ...BASE_EN,
    title: "VisionCraft AI",
    subtitle: "Descubre los prompts secretos detrás de tus imágenes. Obtén descripciones artísticas detalladas para recrear cualquier imagen con IA.",
    uploadTitle: "Haz clic para subir",
    uploadDesc: "o arrastra y suelta (JPG, PNG, WEBP)",
    analyzeBtn: "Generar Prompt",
    analyzing: "Analizando imagen...",
    resultTitle: "Prompt Generado",
    copyBtn: "Copiar",
    copied: "¡Copiado!",
    resetBtn: "Nueva imagen",
    saveImageBtn: "Guardar Imagen",
    tabTranslated: "Traducción",
    tabCustom: "Estilo personalizado",
    complexityLabel: "Nivel de Detalle",
    complexShort: "Conciso",
    complexNormal: "Estándar",
    complexLong: "Análisis Profundo",
    customStyleLabel: "Estilo Objetivo (Opcional)",
    customStylePlaceholder: "ej. Cyberpunk, Van Gogh...",
    goPremium: "Hacerse Premium",
    premiumActive: "PRO Activo",
    premiumModalTitle: "Desbloquear funciones Pro",
    upgradeBtn: "Comprar Premium ($4.99)",
    securePayment: "Pago seguro vía PayPal",
    shareTwitter: "Publicar en X",
    shareInstagram: "Publicar en Instagram",
    sharePinterest: "Guardar en Pinterest",
    shareReddit: "Compartir en Reddit",
    shareSystem: "Compartir",
    themeLight: "Modo Claro",
    themeDark: "Modo Oscuro",
    editPreset: "Editar",
    updateBtn: "Actualizar",
    cancelBtn: "Cancelar",
    galleryTitle: "Prueba estos ejemplos",
    generateVideoBtn: "Generar Video",
    generatingVideo: "Generando video...",
    videoTitle: "Video IA",
    videoError: "Error al generar video."
  },
  de: {
    ...BASE_EN,
    title: "VisionCraft AI",
    subtitle: "Entschlüsseln Sie die Prompts hinter Ihren Bildern. Erhalten Sie detaillierte Beschreibungen, um jedes Bild mit KI neu zu erstellen.",
    uploadTitle: "Klicken zum Hochladen",
    uploadDesc: "oder per Drag & Drop (JPG, PNG, WEBP)",
    analyzeBtn: "Prompt generieren",
    analyzing: "Bild wird analysiert...",
    resultTitle: "Generierter Prompt",
    copyBtn: "Kopieren",
    copied: "Kopiert!",
    resetBtn: "Neues Bild",
    saveImageBtn: "Bild speichern",
    tabTranslated: "Übersetzung",
    tabCustom: "Benutzerdefinierter Stil",
    complexityLabel: "Detailgenauigkeit",
    complexShort: "Prägnant",
    complexNormal: "Standard",
    complexLong: "Tiefenanalyse",
    customStyleLabel: "Zielstil (Optional)",
    customStylePlaceholder: "z.B. Cyberpunk, Van Gogh...",
    goPremium: "Premium werden",
    premiumActive: "PRO Aktiv",
    premiumModalTitle: "Pro-Funktionen freischalten",
    upgradeBtn: "Premium kaufen ($4.99)",
    securePayment: "Sichere Zahlung über PayPal",
    shareTwitter: "Auf X teilen",
    shareInstagram: "Auf Instagram teilen",
    sharePinterest: "Auf Pinterest merken",
    shareReddit: "Auf Reddit teilen",
    shareSystem: "Teilen",
    themeLight: "Heller Modus",
    themeDark: "Dunkler Modus",
    editPreset: "Bearbeiten",
    updateBtn: "Aktualisieren",
    cancelBtn: "Abbrechen",
    galleryTitle: "Versuchen Sie diese Beispiele",
    generateVideoBtn: "Video erstellen",
    generatingVideo: "Video wird erstellt...",
    videoTitle: "KI Video",
    videoError: "Fehler bei der Videoerstellung."
  },
  it: {
    ...BASE_EN,
    title: "VisionCraft AI",
    subtitle: "Rivela i prompt nascosti nei tuoi pixel. Ottieni descrizioni artistiche dettagliate per ricreare qualsiasi immagine con l'IA.",
    uploadTitle: "Clicca per caricare",
    uploadDesc: "o trascina e rilascia (JPG, PNG, WEBP)",
    analyzeBtn: "Genera Prompt",
    analyzing: "Analisi in corso...",
    resultTitle: "Prompt Generato",
    copyBtn: "Copia",
    copied: "Copiato!",
    resetBtn: "Nuova immagine",
    saveImageBtn: "Salva Immagine",
    tabTranslated: "Traduzione",
    tabCustom: "Stile Personalizzato",
    complexityLabel: "Livello di Dettaglio",
    complexShort: "Conciso",
    complexNormal: "Standard",
    complexLong: "Analisi Approfondita",
    customStyleLabel: "Stile Obiettivo (Opzionale)",
    customStylePlaceholder: "es. Cyberpunk, Van Gogh...",
    goPremium: "Passa a Premium",
    premiumActive: "PRO Attivo",
    premiumModalTitle: "Sblocca funzionalità Pro",
    upgradeBtn: "Acquista Premium ($4.99)",
    securePayment: "Pagamento sicuro con PayPal",
    shareTwitter: "Condividi su X",
    shareInstagram: "Condividi su Instagram",
    sharePinterest: "Salva su Pinterest",
    shareReddit: "Condividi su Reddit",
    shareSystem: "Condividi",
    themeLight: "Modalità Chiara",
    themeDark: "Modalità Scura",
    editPreset: "Modifica",
    updateBtn: "Aggiorna",
    cancelBtn: "Annulla",
    galleryTitle: "Prova questi esempi",
    generateVideoBtn: "Genera Video",
    generatingVideo: "Generazione video in corso...",
    videoTitle: "Video IA",
    videoError: "Errore generazione video."
  },
  pt: {
    ...BASE_EN,
    title: "VisionCraft AI",
    subtitle: "Desbloqueie os prompts por trás dos seus pixels. Obtenha descrições artísticas para recriar qualquer imagem com IA.",
    uploadTitle: "Clique para enviar",
    uploadDesc: "ou arraste e solte (JPG, PNG, WEBP)",
    analyzeBtn: "Gerar Prompt",
    analyzing: "Analisando imagem...",
    resultTitle: "Prompt Gerado",
    copyBtn: "Copiar",
    copied: "Copiado!",
    resetBtn: "Nova imagem",
    saveImageBtn: "Salvar Imagem",
    tabTranslated: "Tradução",
    tabCustom: "Estilo Personalizado",
    complexityLabel: "Nível de Detalhe",
    complexShort: "Conciso",
    complexNormal: "Padrão",
    complexLong: "Análise Profunda",
    customStyleLabel: "Estilo Alvo (Opcional)",
    customStylePlaceholder: "ex: Cyberpunk, Van Gogh...",
    goPremium: "Seja Premium",
    premiumActive: "PRO Ativo",
    premiumModalTitle: "Desbloquear recursos Pro",
    upgradeBtn: "Comprar Premium ($4.99)",
    securePayment: "Pagamento seguro via PayPal",
    shareTwitter: "Postar no X",
    shareInstagram: "Postar no Instagram",
    sharePinterest: "Salvar no Pinterest",
    shareReddit: "Compartilhar no Reddit",
    shareSystem: "Compartilhar",
    themeLight: "Modo Claro",
    themeDark: "Modo Escuro",
    editPreset: "Editar",
    updateBtn: "Atualizar",
    cancelBtn: "Cancelar",
    galleryTitle: "Tente estes exemplos",
    generateVideoBtn: "Gerar Vídeo",
    generatingVideo: "Gerando vídeo...",
    videoTitle: "Vídeo IA",
    videoError: "Erro ao gerar vídeo."
  },
  zh: {
    ...BASE_EN,
    title: "VisionCraft AI",
    subtitle: "解锁图像背后的秘密提示词。获取详细的艺术描述，用 AI 完美重现任何画面。",
    uploadTitle: "点击上传图片",
    uploadDesc: "或拖放文件 (JPG, PNG, WEBP)",
    analyzeBtn: "生成提示词",
    analyzing: "正在分析图片...",
    resultTitle: "生成的提示词",
    copyBtn: "复制",
    copied: "已复制！",
    resetBtn: "上传新图片",
    saveImageBtn: "保存图片",
    tabEnglish: "英文提示词",
    tabTranslated: "中文翻译",
    tabCustom: "自定义风格",
    complexityLabel: "详细程度",
    complexShort: "简洁",
    complexNormal: "标准",
    complexLong: "深度分析",
    customStyleLabel: "目标风格 (可选)",
    customStylePlaceholder: "例如：赛博朋克, 梵高...",
    goPremium: "升级高级版",
    premiumActive: "PRO 已激活",
    premiumModalTitle: "解锁专业功能",
    upgradeBtn: "购买高级版 ($4.99)",
    securePayment: "PayPal 安全支付",
    shareTwitter: "分享到 X",
    shareInstagram: "分享到 Instagram",
    sharePinterest: "保存到 Pinterest",
    shareReddit: "分享到 Reddit",
    shareSystem: "分享",
    themeLight: "浅色模式",
    themeDark: "深色模式",
    editPreset: "编辑",
    updateBtn: "更新",
    cancelBtn: "取消",
    galleryTitle: "尝试这些示例",
    generateVideoBtn: "生成视频预览",
    generatingVideo: "正在生成视频...",
    videoTitle: "AI 视频",
    videoError: "视频生成失败。"
  },
  ja: {
    ...BASE_EN,
    title: "VisionCraft AI",
    subtitle: "ピクセルの背後にあるプロンプトを解き明かす。AIであらゆる画像を再現するための詳細な芸術的記述を取得します。",
    uploadTitle: "クリックしてアップロード",
    uploadDesc: "またはドラッグ＆ドロップ (JPG, PNG, WEBP)",
    analyzeBtn: "プロンプトを生成",
    analyzing: "画像を分析中...",
    resultTitle: "生成されたプロンプト",
    copyBtn: "コピー",
    copied: "コピーしました！",
    resetBtn: "新しい画像",
    saveImageBtn: "画像を保存",
    tabEnglish: "英語プロンプト",
    tabTranslated: "翻訳",
    tabCustom: "カスタムスタイル",
    complexityLabel: "詳細レベル",
    complexShort: "簡潔",
    complexNormal: "標準",
    complexLong: "詳細分析",
    customStyleLabel: "ターゲットスタイル (任意)",
    customStylePlaceholder: "例: サイバーパンク, ゴッホ...",
    goPremium: "プレミアムへ",
    premiumActive: "PRO有効",
    premiumModalTitle: "プロ機能をアンロック",
    upgradeBtn: "プレミアムを購入 ($4.99)",
    securePayment: "PayPalによる安全な支払い",
    shareTwitter: "Xで共有",
    shareInstagram: "Instagramで共有",
    sharePinterest: "Pinterestで保存",
    shareReddit: "Redditで共有",
    shareSystem: "共有",
    themeLight: "ライトモード",
    themeDark: "ダークモード",
    editPreset: "編集",
    updateBtn: "更新",
    cancelBtn: "キャンセル",
    galleryTitle: "これらの例を試す",
    generateVideoBtn: "動画プレビュー生成",
    generatingVideo: "動画を生成中...",
    videoTitle: "AI 動画",
    videoError: "動画生成に失敗しました。"
  },
  ko: {
    ...BASE_EN,
    title: "VisionCraft AI",
    subtitle: "이미지 뒤에 숨겨진 프롬프트를 잠금 해제하세요. AI로 모든 이미지를 재생성할 수 있는 상세한 설명을 받으세요.",
    uploadTitle: "이미지 업로드",
    uploadDesc: "또는 드래그 앤 드롭 (JPG, PNG, WEBP)",
    analyzeBtn: "프롬프트 생성",
    analyzing: "이미지 분석 중...",
    resultTitle: "생성된 프롬프트",
    copyBtn: "복사",
    copied: "복사됨!",
    resetBtn: "새 이미지",
    saveImageBtn: "이미지 저장",
    tabEnglish: "영어 프롬프트",
    tabTranslated: "번역",
    tabCustom: "사용자 정의 스타일",
    complexityLabel: "상세 수준",
    complexShort: "간결하게",
    complexNormal: "표준",
    complexLong: "심층 분석",
    customStyleLabel: "목표 스타일 (선택 사항)",
    customStylePlaceholder: "예: 사이버펑크, 반 고흐...",
    goPremium: "프리미엄",
    premiumActive: "PRO 활성",
    premiumModalTitle: "프로 기능 잠금 해제",
    upgradeBtn: "프리미엄 구매 ($4.99)",
    securePayment: "PayPal을 통한 안전한 결제",
    shareTwitter: "X에 공유",
    shareInstagram: "Instagram에 공유",
    sharePinterest: "Pinterest에 저장",
    shareReddit: "Reddit에 공유",
    shareSystem: "공유",
    themeLight: "라이트 모드",
    themeDark: "다크 모드",
    editPreset: "편집",
    updateBtn: "업데이트",
    cancelBtn: "취소",
    galleryTitle: "예제 시도",
    generateVideoBtn: "비디오 미리보기 생성",
    generatingVideo: "비디오 생성 중...",
    videoTitle: "AI 비디오",
    videoError: "비디오 생성 실패."
  },
  nl: {
    ...BASE_EN,
    title: "VisionCraft AI",
    subtitle: "Ontgrendel de prompts achter je pixels. Krijg gedetailleerde artistieke beschrijvingen om elke afbeelding met AI te recreëren.",
    uploadTitle: "Klik om te uploaden",
    uploadDesc: "of sleep een bestand (JPG, PNG, WEBP)",
    analyzeBtn: "Genereer Prompt",
    analyzing: "Afbeelding analyseren...",
    resultTitle: "Gegenereerde Prompt",
    copyBtn: "Kopiëren",
    copied: "Gekopieerd!",
    resetBtn: "Nieuwe afbeelding",
    saveImageBtn: "Afbeelding opslaan",
    tabTranslated: "Vertaling",
    tabCustom: "Aangepaste Stijl",
    complexityLabel: "Detailniveau",
    complexShort: "Beknopt",
    complexNormal: "Standaard",
    complexLong: "Diepe Analyse",
    customStyleLabel: "Doelstijl (Optioneel)",
    customStylePlaceholder: "bijv. Cyberpunk, Van Gogh...",
    goPremium: "Word Premium",
    premiumActive: "PRO Actief",
    premiumModalTitle: "Ontgrendel Pro Functies",
    upgradeBtn: "Koop Premium ($4.99)",
    securePayment: "Veilig betalen via PayPal",
    shareTwitter: "Delen op X",
    shareInstagram: "Delen op Instagram",
    sharePinterest: "Bewaren op Pinterest",
    shareReddit: "Delen op Reddit",
    shareSystem: "Delen",
    themeLight: "Lichte modus",
    themeDark: "Donkere modus",
    editPreset: "Bewerken",
    updateBtn: "Bijwerken",
    cancelBtn: "Annuleren",
    galleryTitle: "Probeer deze voorbeelden",
    generateVideoBtn: "Video Genereren",
    generatingVideo: "Video genereren...",
    videoTitle: "AI Video",
    videoError: "Video genereren mislukt."
  },
  tr: {
    ...BASE_EN,
    title: "VisionCraft AI",
    subtitle: "Görsellerinizin arkasındaki gizli promptları ortaya çıkarın. Herhangi bir resmi yapay zeka ile yeniden oluşturmak için detaylı tarifler alın.",
    uploadTitle: "Yüklemek için tıklayın",
    uploadDesc: "veya sürükleyip bırakın (JPG, PNG, WEBP)",
    analyzeBtn: "Prompt Oluştur",
    analyzing: "Görsel analiz ediliyor...",
    resultTitle: "Oluşturulan Prompt",
    copyBtn: "Kopyala",
    copied: "Kopyalandı!",
    resetBtn: "Yeni Resim",
    saveImageBtn: "Resmi Kaydet",
    tabTranslated: "Çeviri",
    tabCustom: "Özel Stil",
    complexityLabel: "Detay Seviyesi",
    complexShort: "Özet",
    complexNormal: "Standart",
    complexLong: "Detaylı Analiz",
    customStyleLabel: "Hedef Stil (İsteğe Bağlı)",
    customStylePlaceholder: "ör. Cyberpunk, Van Gogh...",
    goPremium: "Premium Ol",
    premiumActive: "PRO Aktif",
    premiumModalTitle: "Profesyonel Özellikleri Aç",
    upgradeBtn: "Premium Satın Al ($4.99)",
    securePayment: "PayPal ile Güvenli Ödeme",
    shareTwitter: "X'te Paylaş",
    shareInstagram: "Instagram'da Paylaş",
    sharePinterest: "Pinterest'te Kaydet",
    shareReddit: "Reddit'te Paylaş",
    shareSystem: "Paylaş",
    themeLight: "Aydınlık Mod",
    themeDark: "Karanlık Mod",
    editPreset: "Düzenle",
    updateBtn: "Güncelle",
    cancelBtn: "İptal",
    galleryTitle: "Bu örnekleri deneyin",
    generateVideoBtn: "Video Önizleme",
    generatingVideo: "Video oluşturuluyor...",
    videoTitle: "YZ Videosu",
    videoError: "Video hatası."
  },
  pl: {
    ...BASE_EN,
    title: "VisionCraft AI",
    subtitle: "Odkryj prompty ukryte w pikselach. Uzyskaj szczegółowe opisy artystyczne, aby odtworzyć dowolny obraz za pomocą AI.",
    uploadTitle: "Kliknij, aby przesłać",
    uploadDesc: "lub przeciągnij i upuść (JPG, PNG, WEBP)",
    analyzeBtn: "Generuj Prompt",
    analyzing: "Analizowanie obrazu...",
    resultTitle: "Wygenerowany Prompt",
    copyBtn: "Kopiuj",
    copied: "Skopiowano!",
    resetBtn: "Nowy obraz",
    saveImageBtn: "Zapisz obraz",
    tabTranslated: "Tłumaczenie",
    tabCustom: "Własny styl",
    complexityLabel: "Poziom szczegółowości",
    complexShort: "Zwięzły",
    complexNormal: "Standard",
    complexLong: "Głęboka analiza",
    customStyleLabel: "Styl docelowy (opcjonalne)",
    customStylePlaceholder: "np. Cyberpunk, Van Gogh...",
    goPremium: "Przejdź na Premium",
    premiumActive: "PRO Aktywne",
    premiumModalTitle: "Odblokuj funkcje Pro",
    upgradeBtn: "Kup Premium ($4.99)",
    securePayment: "Bezpieczna płatność przez PayPal",
    shareTwitter: "Udostępnij na X",
    shareInstagram: "Udostępnij na Instagramie",
    sharePinterest: "Zapisz na Pintereście",
    shareReddit: "Udostępnij na Reddicie",
    shareSystem: "Udostępnij",
    themeLight: "Tryb jasny",
    themeDark: "Tryb ciemny",
    editPreset: "Edytuj",
    updateBtn: "Aktualizuj",
    cancelBtn: "Anuluj",
    galleryTitle: "Wypróbuj te przykłady",
    generateVideoBtn: "Generuj Wideo",
    generatingVideo: "Generowanie wideo...",
    videoTitle: "Wideo AI",
    videoError: "Błąd generowania wideo."
  },
  hi: {
    ...BASE_EN,
    title: "VisionCraft AI",
    subtitle: "अपनी तस्वीरों के पीछे छिपे प्रॉम्प्ट्स को अनलॉक करें। AI के साथ किसी भी छवि को फिर से बनाने के लिए विस्तृत कलात्मक विवरण प्राप्त करें।",
    uploadTitle: "अपलोड करने के लिए क्लिक करें",
    uploadDesc: "या फ़ाइल खींचें (JPG, PNG, WEBP)",
    analyzeBtn: "प्रॉम्प्ट जनरेट करें",
    analyzing: "छवि का विश्लेषण हो रहा है...",
    resultTitle: "जनरेट किया गया प्रॉम्प्ट",
    copyBtn: "कॉपी करें",
    copied: "कॉपी हो गया!",
    resetBtn: "नई छवि",
    saveImageBtn: "छवि सहेजें",
    tabTranslated: "अनुवाद",
    tabCustom: "कस्टम शैली",
    complexityLabel: "विवरण स्तर",
    complexShort: "संक्षिप्त",
    complexNormal: "मानक",
    complexLong: "गहरा विश्लेषण",
    customStyleLabel: "लक्ष्य शैली (वैकल्पिक)",
    customStylePlaceholder: "जैसे: साइबरपंक, वैन गॉग...",
    goPremium: "प्रीमियम बनें",
    premiumActive: "PRO सक्रिय",
    premiumModalTitle: "प्रो फीचर्स अनलॉक करें",
    upgradeBtn: "प्रीमियम खरीदें ($4.99)",
    securePayment: "PayPal द्वारा सुरक्षित भुगतान",
    shareTwitter: "X पर शेयर करें",
    shareInstagram: "Instagram पर शेयर करें",
    sharePinterest: "Pinterest पर सेव करें",
    shareReddit: "Reddit पर शेयर करें",
    shareSystem: "साझा करें",
    themeLight: "लाइट मोड",
    themeDark: "डार्क मोड",
    editPreset: "संपादित करें",
    updateBtn: "अपडेट करें",
    cancelBtn: "रद्द करें",
    galleryTitle: "इन उदाहरणों को आज़माएं",
    generateVideoBtn: "वीडियो पूर्वावलोकन",
    generatingVideo: "वीडियो जनरेट हो रहा है...",
    videoTitle: "AI वीडियो",
    videoError: "वीडियो त्रुटि।"
  },
  vi: {
    ...BASE_EN,
    title: "VisionCraft AI",
    subtitle: "Mở khóa các prompt ẩn sau các pixel. Nhận mô tả nghệ thuật chi tiết để tái tạo bất kỳ hình ảnh nào bằng AI.",
    uploadTitle: "Nhấn để tải lên",
    uploadDesc: "hoặc kéo thả (JPG, PNG, WEBP)",
    analyzeBtn: "Tạo Prompt",
    analyzing: "Đang phân tích...",
    resultTitle: "Prompt đã tạo",
    copyBtn: "Sao chép",
    copied: "Đã sao chép!",
    resetBtn: "Ảnh mới",
    saveImageBtn: "Lưu hình ảnh",
    tabTranslated: "Bản dịch",
    tabCustom: "Phong cách tùy chỉnh",
    complexityLabel: "Mức độ chi tiết",
    complexShort: "Ngắn gọn",
    complexNormal: "Tiêu chuẩn",
    complexLong: "Phân tích sâu",
    customStyleLabel: "Phong cách mục tiêu (Tùy chọn)",
    customStylePlaceholder: "ví dụ: Cyberpunk, Van Gogh...",
    goPremium: "Nâng cấp Premium",
    premiumActive: "Đã kích hoạt PRO",
    premiumModalTitle: "Mở khóa tính năng Pro",
    upgradeBtn: "Mua Premium ($4.99)",
    securePayment: "Thanh toán an toàn qua PayPal",
    shareTwitter: "Chia sẻ lên X",
    shareInstagram: "Chia sẻ lên Instagram",
    sharePinterest: "Lưu vào Pinterest",
    shareReddit: "Chia sẻ lên Reddit",
    shareSystem: "Chia sẻ",
    themeLight: "Chế độ sáng",
    themeDark: "Chế độ tối",
    editPreset: "Chỉnh sửa",
    updateBtn: "Cập nhật",
    cancelBtn: "Hủy",
    galleryTitle: "Thử các ví dụ này",
    generateVideoBtn: "Tạo Video Xem Trước",
    generatingVideo: "Đang tạo video...",
    videoTitle: "Video AI",
    videoError: "Lỗi tạo video."
  },
  th: {
    ...BASE_EN,
    title: "VisionCraft AI",
    subtitle: "ปลดล็อกพรอมต์ที่ซ่อนอยู่เบื้องหลังพิกเซล รับคำอธิบายทางศิลปะโดยละเอียดเพื่อสร้างภาพใหม่ด้วย AI",
    uploadTitle: "คลิกเพื่ออัปโหลด",
    uploadDesc: "หรือลากและวาง (JPG, PNG, WEBP)",
    analyzeBtn: "สร้าง Prompt",
    analyzing: "กำลังวิเคราะห์...",
    resultTitle: "Prompt ที่ได้",
    copyBtn: "คัดลอก",
    copied: "คัดลอกแล้ว!",
    resetBtn: "รูปภาพใหม่",
    saveImageBtn: "บันทึกรูปภาพ",
    tabTranslated: "คำแปล",
    tabCustom: "สไตล์กำหนดเอง",
    complexityLabel: "ระดับรายละเอียด",
    complexShort: "กระชับ",
    complexNormal: "มาตรฐาน",
    complexLong: "วิเคราะห์เชิงลึก",
    customStyleLabel: "สไตล์เป้าหมาย (ทางเลือก)",
    customStylePlaceholder: "เช่น Cyberpunk, Van Gogh...",
    goPremium: "อัปเกรดพรีเมียม",
    premiumActive: "สถานะ PRO",
    premiumModalTitle: "ปลดล็อกฟีเจอร์โปร",
    upgradeBtn: "ซื้อพรีเมียม ($4.99)",
    securePayment: "ชำระเงินปลอดภัยผ่าน PayPal",
    shareTwitter: "แชร์ไปที่ X",
    shareInstagram: "แชร์ไปที่ Instagram",
    sharePinterest: "บันทึกใน Pinterest",
    shareReddit: "แชร์ไปที่ Reddit",
    shareSystem: "แชร์",
    themeLight: "โหมดสว่าง",
    themeDark: "โหมดมืด",
    editPreset: "แก้ไข",
    updateBtn: "อัปเดต",
    cancelBtn: "ยกเลิก",
    galleryTitle: "ลองตัวอย่างเหล่านี้",
    generateVideoBtn: "สร้างวิดีโอตัวอย่าง",
    generatingVideo: "กำลังสร้างวิดีโอ...",
    videoTitle: "วิดีโอ AI",
    videoError: "สร้างวิดีโอไม่สำเร็จ"
  },
  id: {
    ...BASE_EN,
    title: "VisionCraft AI",
    subtitle: "Buka prompt rahasia di balik piksel Anda. Dapatkan deskripsi artistik mendetail untuk membuat ulang gambar apa pun dengan AI.",
    uploadTitle: "Klik untuk unggah",
    uploadDesc: "atau seret dan lepas (JPG, PNG, WEBP)",
    analyzeBtn: "Buat Prompt",
    analyzing: "Menganalisis gambar...",
    resultTitle: "Prompt Dibuat",
    copyBtn: "Salin",
    copied: "Disalin!",
    resetBtn: "Gambar Baru",
    saveImageBtn: "Simpan Gambar",
    tabTranslated: "Terjemahan",
    tabCustom: "Gaya Kustom",
    complexityLabel: "Tingkat Detail",
    complexShort: "Ringkas",
    complexNormal: "Standar",
    complexLong: "Analisis Mendalam",
    customStyleLabel: "Gaya Target (Opsional)",
    customStylePlaceholder: "misal: Cyberpunk, Van Gogh...",
    goPremium: "Jadi Premium",
    premiumActive: "PRO Aktif",
    premiumModalTitle: "Buka Fitur Pro",
    upgradeBtn: "Beli Premium ($4.99)",
    securePayment: "Pembayaran aman via PayPal",
    shareTwitter: "Posting di X",
    shareInstagram: "Posting di Instagram",
    sharePinterest: "Simpan di Pinterest",
    shareReddit: "Bagikan di Reddit",
    shareSystem: "Bagikan",
    themeLight: "Mode Terang",
    themeDark: "Mode Gelap",
    editPreset: "Edit",
    updateBtn: "Perbarui",
    cancelBtn: "Batal",
    galleryTitle: "Coba contoh ini",
    generateVideoBtn: "Buat Pratinjau Video",
    generatingVideo: "Membuat video...",
    videoTitle: "Video AI",
    videoError: "Gagal membuat video."
  }
};

export const INSTAGRAM_LINK = "https://www.instagram.com/panikalastreetmgl/";
